# Generated by Django 5.2.7 on 2025-10-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
