# Generated by Django 5.2.4 on 2025-11-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_productmodel_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_image',
            field=models.URLField(max_length=500),
        ),
    ]
